delete from BOOKING;
delete from ITEMS;
delete from USERS;

ALTER TABLE COMMENTS ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE BOOKING ALTER COLUMN booking_id RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ITEMS ALTER COLUMN item_id RESTART WITH 1;

