CREATE TABLE IF NOT EXISTS USERS (
                                     ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     USER_NAME VARCHAR(100) NOT NULL,
                                     EMAIL VARCHAR(100) NOT NULL,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS ITEMS (
                                     ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     ITEM_NAME VARCHAR(100) NOT NULL,
                                     DESCRIPTION VARCHAR(1000) NOT NULL,
                                     AVAILABLE Boolean NOT NULL,
                                     OWNER_ID BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
                                     REQUEST_ID BIGINT
);

CREATE TABLE IF NOT EXISTS BOOKING (
                                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                       ITEM_ID BIGINT REFERENCES items (id) ON DELETE CASCADE,
                                       BOOKER_ID BIGINT REFERENCES users (id) ON DELETE CASCADE,
                                       STATUS VARCHAR,
                                       START_BOOKING TIMESTAMP WITHOUT TIME ZONE,
                                       END_BOOKING TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS COMMENTS (
                                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                        COMMENT_TEXT VARCHAR,
                                        ITEM_ID BIGINT REFERENCES items (id) ON DELETE CASCADE,
                                        AUTHOR_ID BIGINT REFERENCES users (id) ON DELETE CASCADE,
                                        CREATED_TIME TIMESTAMP WITH TIME ZONE
);
